name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configuração do .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x 

    - name: Restaurar Pacotes e Executar Testes Unitários
      working-directory: ./FichaCadastroSln/FichaCadastroTest
      run: |
        dotnet restore
        dotnet test -v q  # Usando verbosidade "quiet"

    - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    

    #- name: Publicar Artefatos (opcional)
      # Adicione esta etapa se desejar publicar artefatos, como resultados de testes
      # Você pode configurar essa etapa para carregar resultados de testes para um local de armazenamento ou serviço de CI/CD.
